swagger: '2.0'
info:
  title: XSS attack
  description: |
    XSS here
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
